name: display_masjid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  hijri: ^3.0.0
  google_fonts: ^6.2.1
  quran: ^1.2.3
  just_audio: ^0.9.33
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/playlist_quran.json
    - assets/masjid_config.json
    - assets/logo_masjid.png
    - assets/quran_images/
    - assets/quran_audio/
    - assets/surah/
    - assets/google_fonts/
